#!/bin/sh

#docker host reboot:
#dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Reboot" boolean:true

#docker host reboot consolekit environmet:
#dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart boolean:true

#Proxmox shutdown via PVE API (requires PVE token creation, environment variables not yet set up):
#curl "https://<IP>:8006/api2/extjs/nodes/<NodeName>/status" -H "Authorization: PVEAPIToken=<UserName>!<TokenID>=<TokenSecret>" -H "Content-Type: application/x-www-form-urlencoded" --data "command=shutdown" --insecure

HOSTNAME=`hostname`
MSG="$HOSTNAME UPS $UPSNAME initiated Shutdown Sequence"
#
(
   echo "$MSG"
   echo " "
   /sbin/apcaccess status
) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN

#docker host shutdown:
dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.PowerOff" boolean:true

#docker host shutdown consolekit environment:
#dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.PowerOff boolean:true

exit 99